services:
  postgresDB:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: manas
      POSTGRES_PASSWORD: 12345manas
      POSTGRES_DB: pollzydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  valkey:
    image: valkey/valkey:latest
    container_name: valkey
    restart: unless-stopped
    ports:
      - "6379:6379"
volumes:
  postgres_data: